### ISSUE TITLE
Can't solve level 31

### ISSUE THREAD

**Issue by SirJorb** [diceroll123/shapeshiftersolver#1]
So I've reached level 31 (the first 6x6 puzzle), and it seems like the solver just... can't handle it. I left it running overnight for _over 12 hours_ and it still hadn't come to a solution. I worry about how it might handle something like level 100...

Would it be possible to implement something like was used in Kvho's "ss.c" solver? I found mention of it [here](https://shewhoshapes.wordpress.com/), from a blog someone posted in 2008 of their own journey to make a solver, though there didn't seem to be any download links. Kvho's solver was able to tackle level 100 in 994 seconds, while this person's own solver was 3h 20m. Seems like some potential implementation concepts to be applied from these, perhaps?

**Comment by diceroll123** [comment]
Yeah... It turns out it's ***WAY*** better to implement a Shapeshifter solver using linear programming rather than brute forcing.
